project:
  type: book

book:
  title: "Pensamiento Computacional"
  author: "Aldana Rastrelli, Juan Pablo Bulacios, Llamell Mart√≠nez Gorbik, Pablo Notari"
  date: "12/27/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - rules.qmd
    - unidad_1.qmd
    - unidad_2.qmd
    - unidad_3.qmd
    - unidad_4.qmd
    - unidad_5.qmd
    - unidad_6.qmd
    - guia.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



